<?php require 'templates/layout/header.phtml' ?>

<?php require 'templates/form_add_propiedad.phtml' ?>

<div class="container mt-5" style="max-width: 600px;">
    <ul class="list-group">
        <?php foreach ($properties as $property): ?>
            <li class="list-group-item item-task <?php if ($property->finalizada): ?> finished <?php endif ?>">
                <div class="d-flex flex-column">
                    <div>
                        <b>Ubicación: <?= htmlspecialchars($property->ubicacion) ?></b>
                    </div>
                    <div class="d-flex justify-content-end mt-2">
                        <a href="detallePropiedad/<?= $property->id ?>" class="btn btn-success btn-sm mx-1">Ver más detalle</a>
                        <a href="" class="btn btn-warning btn-sm mx-1">Editar</a>
                        <a href="borrarPropiedad/<?= $property->id ?>" class="btn btn-danger btn-sm mx-1">Borrar</a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <p class="text-white mt-3 text-center"><small>Mostrando <?= $count ?> propiedades</small></p>
</div>


<?php require 'templates/layout/footer.phtml' ?>