<?php require 'templates/layout/header.phtml' ?>

<?php require 'templates/form_alta_tarea.phtml' ?>

<ul class="list-group">
    <?php foreach ($tasks as $task): ?>
        <li class="list-group-item item-task <?php if ($task->finalizada): ?> finished <?php endif ?>">
            <div class="label">
                <b>Ubicacion: <?= htmlspecialchars($task->ubicacion) ?></b> | M2: <?= substr($task->m2, 0, 25) ?> | Precio inicial: <?= $task->precio_inicial ?>
            </div>
            <div class="actions">
                <?php if (!$task->id_propietario): ?>
                    <a href="finalizar/<?= $task->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a>
                <?php endif ?>
                <a href="eliminar/<?= $task->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> propiedades</small></p>


<?php require 'templates/layout/footer.phtml' ?>