<?php require 'templates/layout/header.phtml';
$propiedad = $property; ?>

<div class="container mt-4">
    <h1 class="text-center text-white">Detalles de la Propiedad</h1>
    <div class="card text-dark bg-light mb-3">
        <div class="card-header">Información de la Propiedad</div>
        <div class="card-body">
            <h5 class="card-title"><strong>Ubicación:</strong> <?php echo htmlspecialchars($propiedad->ubicacion); ?></h5>
            <p class="card-text"><strong>Metros cuadrados:</strong> <?php echo htmlspecialchars($propiedad->m2); ?> m²</p>
            <p class="card-text"><strong>Modalidad:</strong> <?php echo htmlspecialchars($propiedad->modalidad); ?></p>
            <p class="card-text"><strong>Precio inicial:</strong> $<?php echo htmlspecialchars($propiedad->precio_inicial); ?></p>
            <p class="card-text"><strong>Precio flexible:</strong> <?php echo $propiedad->precio_flex ? 'Sí' : 'No'; ?></p>
            <p class="card-text"><strong>Propietario:</strong> <?php echo htmlspecialchars($propiedad->nombre . ' ' . $propiedad->apellido); ?></p>
            <a href="propiedades" class="btn btn-success">Volver a la lista de propiedades</a>
            <?php if ($this->user && $this->user->user <> NULL): ?>
                <a href="agregarPropiedad" class="btn btn-danger">Seguir modificando propiedades</a>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml'; ?>