<div class="d-flex sutify-content-center flex-column">
    <div class='alert alert-danger text-center' role='alert'>
        <?= $error ?>
    </div>
    <div>
    <a href="propiedades" class="btn btn-success btn-sm">
        <svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 0 24 24" width="20px" fill="#ffffff">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 3l9 8h-3v7h-4v-5h-4v5H6v-7H3l9-8zm0 2.2L6 10.8V18h2v-5h8v5h2v-7.2l-6-5.6z"/>
        </svg>
        Ir a propiedades
    </a>
    <a href="propietarios" class="btn btn-success btn-sm">
        <svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 0 24 24" width="20px" fill="#ffffff">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 12c2.67 0 8 1.34 8 4v2H4v-2c0-2.66 5.33-4 8-4zm0-2c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm0-10C6.48 0 2 4.48 2 10s4.48 10 10 10 10-4.48 10-10S17.52 0 12 0z"/>
        </svg>
        Ir a propietarios
    </a>
</div>

</div>