<?php require 'templates/layout/header.phtml' ?>

<form method='post' action='login'>
    <h3 class="text-light">Loguearse</h3>
    <div class='form-group'>
        <label for='usuario'>Usuario</label>
        <input type='usuario' class='form-control' id='usuario' name='usuario' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-5'>Login</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>