<?php require 'templates/layout/header.phtml';
$id_propiedad = $id;
?>
<div class="container mt-5 text-white" style="max-width: 500px;">
    <form action="editarPropiedad" method="POST">
        <div class="row mb-3">
            <div class="col">
                <input type="hidden" value="<?php echo htmlspecialchars($id_propiedad) ?>" id="id" name="id">
                <label for="ubicacion" class="form-label">Ubicación</label>
                <input type="text" class="form-control form-control-sm" id="ubicacion" name="ubicacion" value="<?php echo htmlspecialchars($property->ubicacion) ?>" required>
            </div>
            <div class="col">
                <label for="precio_inicial" class="form-label">Precio Inicial</label>
                <input type="text" class="form-control form-control-sm" id="precio_inicial" name="precio_inicial" value="<?php echo htmlspecialchars($property->precio_inicial) ?>" required>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <label for="m2" class="form-label">Metros Cuadrados</label>
                <input type="text" class="form-control form-control-sm" id="m2" name="m2" value="<?php echo htmlspecialchars($property->m2) ?>" required>
            </div>
            <div class="col">
                <label for="precio_flexible" class="form-label">Precio Flexible</label>
                <select required name="precio_flexible" class="form-control form-control-sm">
                    <option hidden selected value="<?php echo htmlspecialchars($property->precio_flex)  ?>"><?php echo htmlspecialchars($property->precio_flex) ? 'Sí' : 'No'; ?></option>
                    <option value="">-</option>
                    <option value="0">No</option>
                    <option value="1">Si</option>
                </select>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <label for="modalidad" class="form-label">Modalidad</label>
                <select required name="modalidad" class="form-control form-control-sm">
                    <option hidden selected value="<?php echo htmlspecialchars($property->modalidad) ?>"><?php echo htmlspecialchars($property->modalidad) ?></option>
                    <option value="">-</option>
                    <option value="Venta">Venta</option>
                    <option value="Alquiler">Alquiler</option>
                </select>
            </div>
            <div class="col">
                <label for="propietario" class="form-label">Propietario</label>
                <select required name="propietario" class="form-control form-control-sm">
                    <option hidden selected value="<?php echo htmlspecialchars($property->id_propietario) ?>"><?php echo htmlspecialchars($propertyDetails->nombre . ' ' . $propertyDetails->apellido) ?></option>
                    <option value="">-</option>
                    <?php foreach ($owners as $owner): ?>
                        <option value="<?php echo htmlspecialchars($owner->id); ?>">
                            <?php echo htmlspecialchars($owner->nombre . ' ' . $owner->apellido); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="d-grid">
            <button type="submit" class="btn btn-primary btn-sm mb-2">Editar</button>
            <a href="agregar-modificarPropiedad" class="btn btn-danger btn-sm">Modificar otra propiedad</a>
        </div>
    </form>
</div>
<?php require 'templates/layout/footer.phtml'; ?>