<?php require 'templates/layout/header.phtml';
$error=$error?>

<form method='post' action='login'>
    <h3 class="text-light mt-5">Loguearse</h3>
    <div class='form-group text-white'>
        <label for='usuario'>Usuario</label>
        <input type='usuario' class='form-control' id='usuario' name='usuario' required>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-2'>Login</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>