<?php require 'templates/layout/header.phtml'; ?>
<div class="d-flex flex-column">
    <div class="">
        <h3 class="text-white my-2">Propietarios</h3>
        <ul class=" p-0 gap-3 text-center d-flex">
            <?php foreach ($owners as $owner): ?>
                <li class="rounded list-group-item my-2 bg-light px-3 py-1">
                    <div class="label text-center d-flex flex-column justify-content-center flex-wrap">
                    <?php if (!empty($owner->imagen)): ?>
                                <img src="<?= htmlspecialchars($owner->imagen) ?>" alt="Imagen del propietario" class="img-fluid my-2 px-3 rounded-circle " style="height: 100px; width: 125px;">
                            <?php endif; ?>
                        <b><?= htmlspecialchars($owner->nombre) ?></b>
                        <b><?= htmlspecialchars($owner->apellido) ?></b>
                        <a href="detallePropietario/<?= $owner->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Ver más detalle</a>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <p class="mt-3 text-white"><small>Mostrando <?= $count ?> propietarios registrados</small></p>
    </div>
</div>


<?php require 'templates/layout/footer.phtml'; ?>