<?php require 'templates/layout/header.phtml'; ?>
<div class="d-flex mt-4 gap-3">
    <div class="d-flex flex-column mx-2">
        <h4 class="text-center text-white">Lista de Categorías</h4>
        <ul class="list-group mb-4">
            <?php foreach ($categories as $category): ?>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <?= htmlspecialchars($category->nombre) ?>
                    <a href="eliminar_categoria/<?= $category->id ?>" class="btn btn-danger btn-sm">Eliminar</a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="d-flex flex-column mx-2">
        <h5 class="text-center text-white">Agregar Nueva Categoría</h5>
        <form method="POST" action="agregar_categoria" class="mb-4">
            <div class="mb-3">
                <input type="text" name="nombre" class="form-control" placeholder="Nombre de la categoría" required>
            </div>
            <div class="mb-3">
                <label for="tipo" class="form-label text-white">Tipo de categoría:</label>
                <select name="tipo" id="tipo" class="form-select" required>
                    <option value="">Seleccionar tipo</option>
                    <option value="propietario">Propietario</option>
                    <option value="propiedad">Propiedad</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success">Agregar Categoría</button>
        </form>
    </div>
</div>
<?php require 'templates/layout/footer.phtml'; ?>