<?php require 'templates/layout/header.phtml'; ?>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="text-white my-2">Propiedades</h3> <!-- Título alineado a la izquierda -->
        </div>
        <div class="col-12">
            <ul class="p-0 gap-3 d-flex flex-wrap justify-content-start"> <!-- Cambiado justify-content-center a justify-content-start -->
                <?php foreach ($properties as $property): ?>
                    <li class="rounded list-group-item my-2 bg-light px-3 py-1" style="width: 180px;">
                        <div class="label text-center d-flex flex-column justify-content-center">
                            <b><?= htmlspecialchars($property->ubicacion) ?></b>
                            <b><?= htmlspecialchars($property->modalidad) ?></b>
                            <a href="detallePropiedad/<?= $property->id ?>" type="button" class='btn btn-success btn-sm mt-2'>Ver más detalle</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col-12">
            <p class="text-white mt-3"><small>Mostrando <?= $count ?> propiedades</small></p> <!-- Texto de contador alineado a la izquierda -->
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml'; ?>