<?php require 'templates/layout/header.phtml' ?>
<h4>Ubicacion de las propiedades:</h4>
<ul class="list-group">
    <?php foreach ($tasks as $task): ?>
        <li class="list-group-item item-task <?php if ($task->finalizada): ?> finished <?php endif ?>">
            <div class="label">
                <b><?= htmlspecialchars($task->ubicacion) ?></b>
            </div>
            <a href="detalle/<?= $task->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Ver más detalle</a>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> propiedades disponibles</small></p>


<?php require 'templates/layout/footer.phtml' ?>