<?php require 'templates/layout/header.phtml'; ?>
<div class="d-flex flex-column">
    <div class="">
        <h3 class="text-white my-2">Propiedades</h3>
        <ul class=" p-0 gap-3 text-center d-flex">
            <?php foreach ($properties as $property): ?> 
                <li class="list-group-item my-2 bg-light px-3 py-1"> 
                    <div class="label text-center d-flex flex-column justify-content-center flex-wrap">
                        <b><?= htmlspecialchars($property->ubicacion) ?></b> 
                        <b><?= htmlspecialchars($property->modalidad) ?></b>
                        <a href="detallePropiedad/<?= $property->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Ver más detalle</a> 
                    </div>
                </li>
                <?php endforeach; ?>
            </ul>
            <p class="mt-3 text-white"><small>Mostrando <?= $count ?> propiedades disponibles</small></p>
        </div>
</div>


<?php require 'templates/layout/footer.phtml'; ?>
