<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Inmobiliaria FN</title>
</head>

<body class="bg-dark d-flex flex-column min-vh-100">
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-dark">
            <div class="container-fluid ">
                <a class="navbar-brand text-light" href="home">INMOBILIARIA - FN</a>
                <div class="collapse navbar-collapse " id="navbarNav">
                    <ul class="navbar-nav">
                        <?php if ($this->user && $this->user->user <> NULL): ?>
                            <span class="nav-link border-start text-primary border-secondary border-4">Bienvenido <?= $this->user->user ?> !</span>
                        <?php endif; ?>
                        <li class="nav-item border-start border-end border-secondary border-4">
                            <a class="nav-link text-white" aria-current="page" href="propiedades">Todas las Propiedades</a>
                        </li>
                        <li class="nav-item border-end border-secondary border-4">
                            <a class="nav-link text-white" aria-current="page" href="propietarios">Propietarios</a>
                        </li>
                        <?php if ($this->user && $this->user->user <> NULL): ?>
                            <li class="nav-item border-end border-secondary border-4">
                                <a class="nav-link text-white" aria-current="page" href="categorias">Categorias</a>
                            </li>
                            <li class="nav-item border-end border-secondary border-4">
                                <a class="nav-link text-white" aria-current="page" href="agregarPropiedad">Agregar propiedad</a>
                            </li>
                        <?php endif; ?>
                        <?php if (!empty($this->user && $this->user->user == NULL)): ?>
                            <li class="nav-item border-end border-secondary border-4">
                                <a class="nav-link text-white" aria-current="page" href="login">Loguearse</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->user && $this->user->user <> NULL): ?>
                            <li class="nav-item border-end border-secondary border-4">
                                <a class="nav-link text-danger" href="logout">Salir</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="bg-dark d-flex justify-content-center">